version: 1.0.0.{build}
skip_tags: true
skip_branch_with_pr: true
max_jobs: 8
image: Visual Studio 2017
configuration:
- Debug
- Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
services: iis
install:
- ps: >-
    dotnet restore spectre-upload.sln

    Install-Product node 8 x64

    cd spectre-upload

    npm install

    cd ..
build:
  project: spectre-upload.sln
  parallel: true
  verbosity: minimal
test: off
deploy: off
notifications:
# this publishes to Continuous Integration channel in Glip
- provider: Webhook
  url:
    secure: V16hjhyXfcLNyhNUih9v1Lb4wDly5r6CNNufciMrvllwt0m0rkguf6o4DY7pbdKia/vJGmErvQLdEW0MkzqsAhLWiPY7+Z6qvzFjweP8xNg=
  method: POST
  content_type: application/json
  body: >-
    {
      "icon": "https://www.appveyor.com/assets/img/appveyor-logo-256.png",
      "activity": "AppVeyor for spectre-upload",
      "title": "Build {{buildVersion}} **{{#failed}}failed{{/failed}}{{#passed}}passed{{/passed}}** in {{duration}}",
      "body": "{{#isPullRequest}}Pull request: [#{{pullRequestId}}](https://github.com/spectre-team/spectre-upload/pull/{{pullRequestId}})\n{{/isPullRequest}}Branch: [{{branch}}](https://github.com/spectre-team/spectre-upload/tree/{{branch}})\nCommit: [{{commitId}} {{commitMessage}}](https://github.com/spectre-team/spectre-upload/commit/{{commitId}})\nAuthor: {{commitAuthor}}\n[Build details]({{buildUrl}})"
    }
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true